### ISSUE TITLE
Rules from Symfony 3.2 applys to Symfony 5.4

### ISSUE THREAD

**Issue by astronom** [rectorphp/rector-symfony#134]
This sets contains rules for adding priority as a second argument to `addCompillerPass` method
* https://github.com/rectorphp/rector-symfony/blob/main/config/sets/symfony/symfony33.php#L25
* https://github.com/rectorphp/rector-symfony/blob/main/config/sets/symfony/symfony32.php#L12

When apply rule `$containerConfigurator->import(SymfonyLevelSetList::UP_TO_SYMFONY_54);` this rules also applys but method signature since symfony 3 was changed to https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/DependencyInjection/ContainerBuilder.php#L464 and priority now is the third argument

Diiff
```diff
     protected function build(ContainerBuilder $container): void
     {
-        $container->addCompilerPass(new FooPass());
+        $container->addCompilerPass(new FooPass(), 0);
     }
```

**Comment by samsonasik** [comment]
@astronom by looking at the config, it seems both fill arg position 2, which means third argument (argument start with 0). It possibly due to 2nd argument never exists, so seems just fill it

Could you create failing test case at https://github.com/rectorphp/rector-symfony/tree/main/tests/Set ? 

Thank you.

**Comment by samsonasik** [comment]
@astronom I created PR https://github.com/rectorphp/rector-src/pull/1946 for it.
