### ISSUE TITLE
Upgrading to 0.12.3 gives "Method getExtendedTypes() was not found in reflection of class Symfony\Component\Form\AbstractTypeExtension"

### ISSUE THREAD

**Issue by Bilge** [rectorphp/rector-symfony#61]
It seems that, after Rector finishes its first run after upgrading from 0.11 -> 0.12, almost every file in my project is attributed to an error similar to the following:

> [ERROR] Could not process "src/Kernel.php" file, due to:
         "Method getExtendedTypes() was not found in reflection of class Symfony\Component\Form\AbstractTypeExtension.".
         On line: 328

Of course, the source file (`Kernel.php`) is different in each case, but otherwise the error is the same for every single file. Many of these files do not even appear to be tangentially related to the Form component in any way, so I have no idea what is going on.

This occurs on Symfony 4.4.33.

**Comment by TomasVotruba** [comment]
Thanks for reporting!

That's probably because Kernel contains optional dependency on symfony/forms. That's unfortunate design flaw of Kernel, as Rector does not know this class is optional.

The quick fix would be:

```bash
composer require symfony/form --dev
```

Slow fix would be to fake this class somehow. Could you share minimal reproducible repository on Github? We'll check it

**Comment by Bilge** [comment]
I believe it has nothing to do with the Kernel. It affects almost every file in my project.

**Comment by TomasVotruba** [comment]
I see. Could you share reproducible repository so we can reproduce the bug?

**Comment by spras** [comment]
> I see. Could you share reproducible repository so we can reproduce the bug?

https://github.com/spras/symfony_4_rector_issue a fresh install of symfony 4.4
rector is installed with SymfonySet up to 4.2

**Comment by Bilge** [comment]
@TomasVotruba Have you had a chance to look at this? Since it's blocking the Rector upgrade, it's quite major for us.

**Comment by TomasVotruba** [comment]
@Bilge I haven't found time yet. Failing CI job would speed it up

**Comment by MisatoTremor** [comment]
The problem here seems that `AbstractTypeExtension::getExtendedTypes()` is indeed not implemented in the Form component until [5.0](https://github.com/symfony/symfony/blob/5.0/src/Symfony/Component/Form/FormTypeExtensionInterface.php), but not using itis deprecated since [4.2](https://github.com/symfony/symfony/blob/4.2/src/Symfony/Component/Form/FormTypeExtensionInterface.php).
I have already updated our code to use `getExtendedTypes()` instead of `getExtendedType()`, so I see why this could cause the error. Interesting though it also seems to trigger wehn mnot even using ist as in @spras example.

**Comment by mkrauser** [comment]
I digged into this, the problematic rector is this one: 

```
new \Rector\Renaming\ValueObject\MethodCallRename('Symfony\\Component\\Form\\AbstractTypeExtension', 'getExtendedType', 'getExtendedTypes')
```

from the Symfony42 Set. 

As far as I understand, the problem is, that rector looks up the class-hierarchy and tries to find the method 'getExtendedTypes'. The hasMethod-Call in ClassChildAnalyzer::hasChildClassMethod returns true, due to the @method Doc-Annotation in FormTypeExtensionInterface.
In the next line, the ClassChildAnalyzer tries to get a MethodReflection-Object for the function, which fails because it does not really exist yet (only the @method Doc-Annotation), and that's what causes the exception.

Here's the code I'm talking about (also see [here](https://github.com/rectorphp/rector-src/blob/f451b0b8e1e6761ec7f50809745d44d01caba66d/packages/FamilyTree/NodeAnalyzer/ClassChildAnalyzer.php#L23)):
```
if (!$childClassReflection->hasMethod($methodName)) {  // the hasMethod-Call returns true, due to the @method Doc-Annotation in FormTypeExtensionInterface
     continue;
}
// then this line throws the Exception, because the function does not really exist
$constructorReflectionMethod = $childClassReflection->getNativeMethod($methodName);
```

**Comment by TomasVotruba** [comment]
@mkrauser Great catch, thank you!
I made PR to fix this one https://github.com/rectorphp/rector-src/pull/1336
